---
title: "TidyTuesday 2022/05 - Dog Breeds"
author: "Johan Ibrahim"
date: "9th February 2022"
output:
  html_document:
  theme: paper
highlight: kate
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, 
                      dev = "ragg_png", res = 500, retina = 1)
```

```{r prep, message=FALSE, warning=FALSE}
## packages
library(tidyverse)
library(ggtext)
library(ggrepel)
library(patchwork)
library(systemfonts)
library(ggimage)
library(geomtextpath)
library(stringr)
library(showtext)
library(cowplot)
library(MetBrewer)
theme_set(theme_minimal(base_size = 19, base_family = "Girassol"))
theme_update(
  text = element_text(color = "grey12"),
  axis.title = element_blank(),
  axis.text.x = element_text(family = "Iosevka Curly"),
  axis.text.y = element_blank(),
  panel.grid.major.y = element_blank(),
  panel.grid.minor = element_blank(),
  plot.margin = margin(20, 5, 10, 10),
  plot.subtitle = element_textbox_simple(family = "Roboto Condensed", size = 14,
                                         lineheight = 1.6),
  plot.title.position = "plot",
  plot.caption = element_text(family = "Iosevka Curly", color = "#b40059", hjust = .5,
                              size = 10, margin = margin(35, 0, 0, 0))
)
```

## Data

```{r data}

breed_traits <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-02-01/breed_traits.csv') 

breed_rank_all <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-02-01/breed_rank.csv')
 
```

```{r prep-data}


```

```{r plot}

```

